# greetd configuration with autologin

[terminal]
vt = 1

[default_session]
# Autologin configuration
command = "uwsm start hyprland-uwsm.desktop"
user = "fcalell"

# Uncomment below and comment the above [default_session] to use tuigreet instead of autologin
# [default_session]
# command = "tuigreet --time --remember --remember-session --cmd 'uwsm start hyprland-uwsm.desktop'"
# user = "greeter"
